language: java

# for now we depend upon deprecated CI infrastructure (to keep builds green): https://blog.travis-ci.com/2017-05-04-precise-image-updates
group: deprecated-2017Q1

before_install:
- wget https://dl.dropboxusercontent.com/u/7897865/apache-maven-3.3.9.zip
- unzip -qq apache-maven-3.3.9.zip
- export M2_HOME=$PWD/apache-maven-3.3.9
- export PATH=$M2_HOME/bin:$PATH
- mvn -version
- script/travis/before_install_apt-fast.sh
- sudo apt-fast update -qq -y
- script/travis/before_install_firebird.sh
- script/travis/before_install_oracle.sh
- groovy script/travis/generateMavenSettings.groovy
before_script:
- script/travis/before_script_firebird.sh
- script/travis/before_script_mysql.sh
- script/travis/before_script_postgres.sh
- script/travis/before_script_oracle.sh
env:
  global:
  - LD_LIBRARY_PATH=/home/db2inst1/sqllib/lib64/
install:
- mvn -q -B dependency:resolve-plugins --settings ~/.m2/p6spySettings.xml
- mvn -q -B dependency:resolve --settings ~/.m2/p6spySettings.xml
jdk:
- oraclejdk7
- openjdk7
- oraclejdk8
language: java
notifications:
  email: false
  slack:
    rooms: flakycov:U2MeVOPjdi4up1U793ubeIUZ
    template:
    - Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository}@%{branch} by %{author} %{result} in %{duration}
    - 'dashbot: %{repository_name} %{build_id}'
script:
- mvn -B test -P travis --settings ~/.m2/p6spySettings.xml
